# Generated by Django 4.1.7 on 2023-03-20 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forgery', '0003_images_ela_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='ela_image',
            field=models.ImageField(default='upload/tamp2r.jpg', upload_to='upload/'),
        ),
    ]
